version: '3'
services:
  api:
    environment:
      - DEBUG=True
      - DB_ENGINE=django.db.backends.postgresql
      - DB_HOSTNAME=db
      - DB_USER=fresco
      - DB_PASSWORD=db_pass
      - DB_NAME=fresco
