# Generated by Django 4.1.5 on 2023-01-10 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instruction',
            unique_together={('step_number', 'recipe')},
        ),
    ]
