# Generated by Django 4.1.5 on 2023-01-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_alter_instruction_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
