# Generated by Django 4.1.5 on 2023-01-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_alter_ingredient_id_alter_instruction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('gr', 'Grams'), ('kg', 'Kilograms'), ('tbs', 'Table Spoons'), ('oz', 'Ounces'), ('mL', 'Milliliters')], max_length=10),
        ),
    ]
